// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file helloworld/v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file helloworld/v1/helloworld.proto.
 */
export const file_helloworld_v1_helloworld: GenFile = /*@__PURE__*/
  fileDesc("Ch5oZWxsb3dvcmxkL3YxL2hlbGxvd29ybGQucHJvdG8SDWhlbGxvd29ybGQudjEiLQodR3JlZXRlclNlcnZpY2VTYXlIZWxsb1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIxCh5HcmVldGVyU2VydmljZVNheUhlbGxvUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCTKZAQoOR3JlZXRlclNlcnZpY2UShgEKCFNheUhlbGxvEiwuaGVsbG93b3JsZC52MS5HcmVldGVyU2VydmljZVNheUhlbGxvUmVxdWVzdBotLmhlbGxvd29ybGQudjEuR3JlZXRlclNlcnZpY2VTYXlIZWxsb1Jlc3BvbnNlIh2C0+STAhcSFS92MS9oZWxsb3dvcmxkL3tuYW1lfUI6WjhnaXRodWIuY29tL2phdmllcnRlbGlvei9ncnBjLXNlcnZpY2UtdGVtcGxhdGUvaGVsbG93b3JsZGIGcHJvdG8z", [file_google_api_annotations]);

/**
 * GreeterServiceSayHelloRequest represents the input for the SayHello method.
 *
 * Fields:
 *   - `name`: The name of the person to greet. This should be passed as a path parameter.
 *
 * @generated from message helloworld.v1.GreeterServiceSayHelloRequest
 */
export type GreeterServiceSayHelloRequest = Message<"helloworld.v1.GreeterServiceSayHelloRequest"> & {
  /**
   * The name of the person to greet. This should be passed as a path parameter.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message helloworld.v1.GreeterServiceSayHelloRequest.
 * Use `create(GreeterServiceSayHelloRequestSchema)` to create a new message.
 */
export const GreeterServiceSayHelloRequestSchema: GenMessage<GreeterServiceSayHelloRequest> = /*@__PURE__*/
  messageDesc(file_helloworld_v1_helloworld, 0);

/**
 * GreeterServiceSayHelloResponse represents the output from the SayHello method.
 *
 * Fields:
 *   - `message`: A greeting message that includes the user's name.
 *
 * @generated from message helloworld.v1.GreeterServiceSayHelloResponse
 */
export type GreeterServiceSayHelloResponse = Message<"helloworld.v1.GreeterServiceSayHelloResponse"> & {
  /**
   * The greeting message to be returned to the user.
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message helloworld.v1.GreeterServiceSayHelloResponse.
 * Use `create(GreeterServiceSayHelloResponseSchema)` to create a new message.
 */
export const GreeterServiceSayHelloResponseSchema: GenMessage<GreeterServiceSayHelloResponse> = /*@__PURE__*/
  messageDesc(file_helloworld_v1_helloworld, 1);

/**
 * GreeterService provides a simple greeting API.
 *
 * @generated from service helloworld.v1.GreeterService
 */
export const GreeterService: GenService<{
  /**
   * SayHello sends a greeting message to the user.
   *
   * This method expects a GET request with the user's name as a path parameter.
   * The server will respond with a greeting message.
   *
   * Request:
   *   - `name`: The name of the person to greet. This should be passed as a path parameter.
   *
   * Response:
   *   - `message`: A greeting message that includes the user's name.
   *
   * Possible HTTP responses:
   *   - 200: The request was successful, and a greeting message is returned.
   *   - 400: The request was malformed, usually because the 'name' parameter is missing.
   *   - 401: Unauthorized request, typically due to missing or invalid authentication credentials.
   *   - 500: Internal server error, indicating a problem on the server side.
   *
   * Example:
   *   GET /v1/helloworld/John
   *
   * Response:
   *   {
   *     "message": "Hello, John!"
   *   }
   *
   * @generated from rpc helloworld.v1.GreeterService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof GreeterServiceSayHelloRequestSchema;
    output: typeof GreeterServiceSayHelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_helloworld_v1_helloworld, 0);

