# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld/v1/helloworld.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'helloworld/v1/helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ehelloworld/v1/helloworld.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"3\n\x1dGreeterServiceSayHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\":\n\x1eGreeterServiceSayHelloResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2\x99\x01\n\x0eGreeterService\x12\x86\x01\n\x08SayHello\x12,.helloworld.v1.GreeterServiceSayHelloRequest\x1a-.helloworld.v1.GreeterServiceSayHelloResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/helloworld/{name}B:Z8github.com/javiertelioz/grpc-service-template/helloworldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld.v1.helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/javiertelioz/grpc-service-template/helloworld'
  _globals['_GREETERSERVICE'].methods_by_name['SayHello']._loaded_options = None
  _globals['_GREETERSERVICE'].methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\027\022\025/v1/helloworld/{name}'
  _globals['_GREETERSERVICESAYHELLOREQUEST']._serialized_start=79
  _globals['_GREETERSERVICESAYHELLOREQUEST']._serialized_end=130
  _globals['_GREETERSERVICESAYHELLORESPONSE']._serialized_start=132
  _globals['_GREETERSERVICESAYHELLORESPONSE']._serialized_end=190
  _globals['_GREETERSERVICE']._serialized_start=193
  _globals['_GREETERSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
