// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: helloworld/v1/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreeterService_SayHello_FullMethodName = "/helloworld.v1.GreeterService/SayHello"
)

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GreeterService provides a simple greeting API.
type GreeterServiceClient interface {
	// SayHello sends a greeting message to the user.
	//
	// This method expects a GET request with the user's name as a path parameter.
	// The server will respond with a greeting message.
	//
	// Request:
	//   - `name`: The name of the person to greet. This should be passed as a path parameter.
	//
	// Response:
	//   - `message`: A greeting message that includes the user's name.
	//
	// Possible HTTP responses:
	//   - 200: The request was successful, and a greeting message is returned.
	//   - 400: The request was malformed, usually because the 'name' parameter is missing.
	//   - 401: Unauthorized request, typically due to missing or invalid authentication credentials.
	//   - 500: Internal server error, indicating a problem on the server side.
	//
	// Example:
	//
	//	GET /v1/helloworld/John
	//
	// Response:
	//
	//	{
	//	  "message": "Hello, John!"
	//	}
	SayHello(ctx context.Context, in *GreeterServiceSayHelloRequest, opts ...grpc.CallOption) (*GreeterServiceSayHelloResponse, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) SayHello(ctx context.Context, in *GreeterServiceSayHelloRequest, opts ...grpc.CallOption) (*GreeterServiceSayHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreeterServiceSayHelloResponse)
	err := c.cc.Invoke(ctx, GreeterService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServiceServer is the server API for GreeterService service.
// All implementations must embed UnimplementedGreeterServiceServer
// for forward compatibility.
//
// GreeterService provides a simple greeting API.
type GreeterServiceServer interface {
	// SayHello sends a greeting message to the user.
	//
	// This method expects a GET request with the user's name as a path parameter.
	// The server will respond with a greeting message.
	//
	// Request:
	//   - `name`: The name of the person to greet. This should be passed as a path parameter.
	//
	// Response:
	//   - `message`: A greeting message that includes the user's name.
	//
	// Possible HTTP responses:
	//   - 200: The request was successful, and a greeting message is returned.
	//   - 400: The request was malformed, usually because the 'name' parameter is missing.
	//   - 401: Unauthorized request, typically due to missing or invalid authentication credentials.
	//   - 500: Internal server error, indicating a problem on the server side.
	//
	// Example:
	//
	//	GET /v1/helloworld/John
	//
	// Response:
	//
	//	{
	//	  "message": "Hello, John!"
	//	}
	SayHello(context.Context, *GreeterServiceSayHelloRequest) (*GreeterServiceSayHelloResponse, error)
	mustEmbedUnimplementedGreeterServiceServer()
}

// UnimplementedGreeterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterServiceServer struct{}

func (UnimplementedGreeterServiceServer) SayHello(context.Context, *GreeterServiceSayHelloRequest) (*GreeterServiceSayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServiceServer) mustEmbedUnimplementedGreeterServiceServer() {}
func (UnimplementedGreeterServiceServer) testEmbeddedByValue()                        {}

// UnsafeGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServiceServer will
// result in compilation errors.
type UnsafeGreeterServiceServer interface {
	mustEmbedUnimplementedGreeterServiceServer()
}

func RegisterGreeterServiceServer(s grpc.ServiceRegistrar, srv GreeterServiceServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreeterService_ServiceDesc, srv)
}

func _GreeterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreeterServiceSayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayHello(ctx, req.(*GreeterServiceSayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreeterService_ServiceDesc is the grpc.ServiceDesc for GreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreeterService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/helloworld.proto",
}
